/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 15.2 		*/
/*  Created On : 10-nov.-2024 5:51:41 p. m. 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

DROP TABLE IF EXISTS "Autor" CASCADE
;

DROP TABLE IF EXISTS "Categoria" CASCADE
;

DROP TABLE IF EXISTS "Cliente" CASCADE
;

DROP TABLE IF EXISTS "Libro" CASCADE
;

DROP TABLE IF EXISTS "Prestamo" CASCADE
;

DROP TABLE IF EXISTS "Prestamo_Libro" CASCADE
;

/* Create Tables */

CREATE TABLE "Autor"
(
	"idAutor" smallint NOT NULL,
	nombre varchar(50) NOT NULL,
	"paisOrigen" varchar(30) NOT NULL
)
;

CREATE TABLE "Categoria"
(
	"idCategoria" smallint NOT NULL,
	"nombreCategoria" varchar(50) NOT NULL,
	descripcion varchar(50) NOT NULL
)
;

CREATE TABLE "Cliente"
(
	"idCliente" smallint NOT NULL,
	nombre varchar(50) NOT NULL,
	correo varchar(50) NOT NULL,
	telefono smallint NOT NULL,
	"estadoCuenta" boolean NOT NULL
)
;

CREATE TABLE "Libro"
(
	"idLibro" smallint NOT NULL,
	titulo varchar(50) NOT NULL,
	"anioPublicacion" varchar(50) NOT NULL,
	disponibilidad varchar(50) NOT NULL,
	descripcion varchar(200) NOT NULL,
	"idCategoriaFK" smallint NOT NULL,
	"idAutorFK" smallint NOT NULL,
	"idPrestamo" smallint NULL
)
;

CREATE TABLE "Prestamo"
(
	"idPrestamo" smallint NOT NULL,
	"fechaInicioPrestamo" date NOT NULL,
	"fehcFinPrestamo" date NOT NULL
)
;

CREATE TABLE "Prestamo_Libro"
(
	"idPrestamo" smallint NOT NULL,
	"idLibro" smallint NOT NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE "Autor" ADD CONSTRAINT "PK_Autor"
	PRIMARY KEY ("idAutor")
;

ALTER TABLE "Categoria" ADD CONSTRAINT "PK_Categoria"
	PRIMARY KEY ("idCategoria")
;

ALTER TABLE "Cliente" ADD CONSTRAINT "PK_Cliente"
	PRIMARY KEY ("idCliente")
;

ALTER TABLE "Libro" ADD CONSTRAINT "PK_Libro"
	PRIMARY KEY ("idLibro")
;

ALTER TABLE "Prestamo" ADD CONSTRAINT "PK_Prestamo"
	PRIMARY KEY ("idPrestamo")
;

ALTER TABLE "Prestamo_Libro" ADD CONSTRAINT "PK_Prestamo_Libro"
	PRIMARY KEY ("idPrestamo","idLibro")
;

/* Create Foreign Key Constraints */

ALTER TABLE "Libro" ADD CONSTRAINT "idAutorFK"
	FOREIGN KEY ("idAutorFK") REFERENCES "Autor" ("idAutor") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Libro" ADD CONSTRAINT "idCategoriaFK"
	FOREIGN KEY ("idCategoriaFK") REFERENCES "Categoria" ("idCategoria") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Prestamo" ADD CONSTRAINT "idClienteFK"
	FOREIGN KEY ("idPrestamo") REFERENCES "Cliente" ("idCliente") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Prestamo_Libro" ADD CONSTRAINT "idLibroFK"
	FOREIGN KEY ("idLibro") REFERENCES "Libro" ("idLibro") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Prestamo_Libro" ADD CONSTRAINT "idPrestamoFK"
	FOREIGN KEY ("idPrestamo") REFERENCES "Prestamo" ("idPrestamo") ON DELETE No Action ON UPDATE No Action
;
